import React,{useEffect,useState} from 'react'; import { me, uploadProfile, createDeposit, myDeposits, startBot, stopBot } from '../api'
export default function Dashboard(){ const [user,setUser]=useState(null); const [amount,setAmount]=useState(''); const [wallet,setWallet]=useState('YOUR_WALLET_ADDRESS_HERE'); const [method,setMethod]=useState('mpesa'); const [file,setFile]=useState(null); const [deposits,setDeposits]=useState([]); const [botStatus,setBotStatus]=useState(false);
async function load(){ try{ const u=await me(); setUser(u); setBotStatus(u.botRunning); const d=await myDeposits(); setDeposits(d); if(u.trustWallet) setWallet(u.trustWallet) }catch(e){} }
useEffect(()=>{ load() },[])
async function doUpload(e){ e.preventDefault(); if(!file) return alert('Choose file'); await uploadProfile(file); await load(); alert('Uploaded') }
async function doDeposit(e){ e.preventDefault(); await createDeposit(amount,wallet,method); setAmount(''); await load(); alert('Deposit submitted') }
async function handleStart(){ try{ const r=await startBot(); alert(r.message); setBotStatus(true) }catch(err){ alert(err.response?.data?.message || err.message) } }
async function handleStop(){ try{ const r=await stopBot(); alert(r.message); setBotStatus(false) }catch(err){ alert(err.response?.data?.message || err.message) } }
return (<div className='grid'><div className='card'><h3>Profile</h3>{user?.profileUrl ? <img src={(import.meta.env.VITE_API_BASE||'http://localhost:4000')+user.profileUrl} style={{width:120,height:120,borderRadius:12,objectFit:'cover'}}/> : <div className='badge'>No image</div>}<p><strong>{user?.name}</strong><br/>{user?.email}</p><form onSubmit={doUpload}><input type='file' accept='image/*' onChange={e=>setFile(e.target.files[0])}/><div style={{height:8}}/><button className='btn'>Upload profile</button></form></div><div className='card'><h3>Deposit</h3><p className='badge'>Send to: <strong>{wallet}</strong></p><form onSubmit={doDeposit}><select className='input' value={method} onChange={e=>setMethod(e.target.value)}><option value='mpesa'>M-Pesa</option><option value='binance'>Binance</option><option value='paypal'>PayPal</option><option value='card'>Card</option><option value='bank'>Bank Transfer</option></select><div style={{height:8}}/><input className='input' placeholder='Amount' value={amount} onChange={e=>setAmount(e.target.value)} /><div style={{height:8}}/><input className='input' placeholder='Your wallet (optional)' value={wallet} onChange={e=>setWallet(e.target.value)} /><div style={{height:8}}/><button className='btn'>Submit deposit</button></form><div style={{height:12}}/><div><strong>Bot status:</strong> {botStatus ? <span className='badge'>Running</span> : <span className='badge'>Stopped</span>}<div style={{height:8}}/>{botStatus ? <button className='btn' onClick={handleStop}>Stop Bot</button> : <button className='btn' onClick={handleStart}>Start Bot</button>}</div></div><div className='card' style={{gridColumn:'1 / -1'}}><h3>Your deposits</h3><table className='table'><thead><tr><th>Amount</th><th>Method</th><th>Status</th><th>Date</th></tr></thead><tbody>{deposits.map(d=>(<tr key={d.id}><td>${d.amount}</td><td>{d.method}</td><td><span className='badge'>{d.status}</span></td><td>{new Date(d.createdAt).toLocaleString()}</td></tr>))}</tbody></table></div></div>) }
